swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
  contact:
    email: "jlanglade@pixbuf.net"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
- "http"
basePath: "/"

# Paths supported by the server application
paths:
  /password:
    post:
      tags:
      - "Password"
      summary: "Generate strong passwords"
      description: "A simple API endpoint designed to generate strong passswords"
      operationId: "app.password.generate"
      parameters:
      - name: "length"
        in: "query"
        description: "Length of passwords"
        required: False
        type: "integer"
        format: "int32"
        default: 16
        maximum: 4096
        minimum: 8
      - name: "count"
        in: "query"
        description: "Count of passwords to generate"
        required: False
        type: "integer"
        format: "int32"
        default: 5
        maximum: 255
        minimum: 1
      - name: "constraints"
        in: "body"
        required: False
        schema:
          $ref: "#/definitions/Constraints"
      produces:
      - "application/json"
      responses:
        "200":
          description: ""
          schema:
            type: "array"
            items:
              type: "string"
  /password/validate:
    post:
      tags:
      - "Password"
      summary: "Validate a password against a policy"
      description: "A simple API endpoint designed to generate strong passswords"
      operationId: "app.password.validate"
      parameters:
      - name: "password"
        in: "query"
        description: "Password to validate"
        required: True
        type: "string"
      - name: "policy"
        in: "body"
        required: False
        schema:
          $ref: "#/definitions/Policy"
      produces:
      - "application/json"
      responses:
        200:
          description: ""
          schema:
            type: "boolean"
definitions:
  Constraints:
    type: "object"
    description: "Contains password generation constraints"
    properties:
    properties:
      lowercase:
        type: "integer"
        format: "int32"
        description: "Minimum number of lowercase characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      uppercase:
        type: "integer"
        format: "int32"
        description: "Minimum number of uppercase characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      digits:
        type: "integer"
        format: "int32"
        description: "Minimum number of digits characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      punctuation:
        type: "integer"
        format: "int32"
        description: "Minimum number of punctuation characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      excluded_chars:
        type: "string"
        description: "List of characters to exclude front generation"
        example: "/iL%"
        default: ""
  Policy:
    type: "object"
    description: "Contains policy definition"
    default:
      lowercase: 1
      uppercase: 1
      digits: 1
      punctuation: 1
      excluded_chars: ""
      length:
        min: 16
        max: 2048
    properties:
      lowercase:
        type: "integer"
        format: "int32"
        description: "Minimum number of lowercase characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      uppercase:
        type: "integer"
        format: "int32"
        description: "Minimum number of uppercase characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      digits:
        type: "integer"
        format: "int32"
        description: "Minimum number of digits characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      punctuation:
        type: "integer"
        format: "int32"
        description: "Minimum number of punctuation characters"
        example: 1
        default: 1
        minimum: 0
        maximum: 4096
      excluded_chars:
        type: "string"
        description: "List of characters to exclude front generation"
        example: "/iL%"
        default: ""
      length:
        type: "object"
        properties:
          min:
            type: "integer"
            format: "int32"
            description: "Minimum length of the password"
            example: 8
            default: 16
            minimum: 8
            maximum: 4096
          max:
            type: "integer"
            format: "int32"
            description: "Maximum length of the password"
            example: 64
            default: 2048
            minimum: 8
            maximum: 4096
